name: unit-test

on:
  push:
    paths:
      - "**.py"
      - ".github/workflows/unit-test.yaml"

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip3 install poetry && \
          poetry config virtualenvs.create false && \
          poetry install
      - name: Execute unit test with coverage
        working-directory: .
        run: pytest -v --cov --cov-report=term-missing unit_tests
